INSERT INTO categories(name) VALUES 
    ('Agriculture & Livestock'),
    ('Food & Related Products'),
    ('Coffee bars, Clubs and Related services'),
    ('Heavy Industry'),
    ('Energy &amp, Raw Materials'),
    ('Vehicles &amp, Transport'),
    ('Chemical Industry'),
    ('Construction'),
    ('Public Works (Construction)'),
    ('Public Works (Services)'),
    ('Wood, Furniture and Other similar products'),
    ('Leather, Textile &amp, Clothing'),
    ('Information, Communication &amp, Technology'),
    ('Telecommunications Industry'),
    ('Photography, Printing &amp, Publishing'),
    ('Luxury &amp, Leisure Products'),
    ('Travel, Tourism &amp, Leisure'),
    ('Marketing, Avdertising &amp, the Media'),
    ('Banking, Finance &amp, Insurance'),
    ('Legal services'),
    ('Health'),
    ('Education'),
    ('Trading services'),
    ('Sport'),
    ('Ecology &amp, Environment'),
    ('Youth &amp, Sport'),
    ('Social protection of youngsters'),
    ('Humanitarian aid'),
    ('Research'),
    ('Advocacy'),
    ('Youth participatin in decission making'),
    ('Culture and Art'),
    ('Primary health protection and prevention'),
    ('Youth employment &amp, Entrepreneuership'),
    ('Rural development'),
    ('Gender equality and LGBTQI rights'),
    ('Marginalized groups'),
    ('Handicrafts'),
    ('Human rights'),
    ('Youth rights'),
    ('Agriculture');